name: build-preview
run-name: Build Pull Request Preview

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PREVIEWS_BRANCH: pr-preview
  PREVIEWS_FOLDER: preview

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          # Checkout the head branch of the PR
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs and dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build and deploy preview site
        run: |
          # Build and deploy to the preview branch
          mkdocs gh-deploy --clean --force --remote-branch ${{ env.PREVIEWS_BRANCH }} \
            --message "Deploy preview for PR #${{ github.event.pull_request.number }}" \
            --config-file mkdocs.yml

      - name: Post PR Comment with Preview Link
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **Preview Available!**
            A preview of this pull request is available at:
            [Preview Link](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.PREVIEWS_FOLDER }}/pr-${{ github.event.pull_request.number }}/)
